import Any from "./Any";
import Between from "./Between";
import Boolean from "./Boolean";
import ByteString from "./ByteString";
import CacheFor from "./CacheFor";
import CacheReverseExpression from "./CacheReverseExpression";
import CaseWhen from "./CaseWhen";
import CaseWhenElement from "./CaseWhenElement";
import Cast from "./Cast";
import Column from "./Column";
import ColumnLink from "./ColumnLink";
import Comment from "./Comment";
import DataType from "./DataType";
import DollarString from "./DollarString";
import DoubleQuotes from "./DoubleQuotes";
import Exists from "./Exists";
import Expression from "./Expression";
import ExpressionElement from "./ExpressionElement";
import Extract from "./Extract";
import File from "./File";
import FilePathElement from "./FilePathElement";
import FromItem from "./FromItem";
import FunctionCall from "./FunctionCall";
import FunctionLink from "./FunctionLink";
import GroupByElement from "./GroupByElement";
import GroupByElementContent from "./GroupByElementContent";
import In from "./In";
import Interval from "./Interval";
import Join from "./Join";
import ObjectLink from "./ObjectLink";
import ObjectName from "./ObjectName";
import Operator from "./Operator";
import OrderByElement from "./OrderByElement";
import PgArray from "./PgArray";
import PgNull from "./PgNull";
import PgNumber from "./PgNumber";
import SchemaName from "./SchemaName";
import SchemaTable from "./SchemaTable";
import Select from "./Select";
import SelectFetch from "./SelectFetch";
import SingleQuotesString from "./SingleQuotesString";
import SquareBrackets from "./SquareBrackets";
import Substring from "./Substring";
import SystemVariable from "./SystemVariable";
import TableLink from "./TableLink";
import Union from "./Union";
import ValueItem from "./ValueItem";
import ValuesRow from "./ValuesRow";
import WindowDefinition from "./WindowDefinition";
import WindowDefinitionFrame from "./WindowDefinitionFrame";
import WindowDefinitionFrameElement from "./WindowDefinitionFrameElement";
import WindowItem from "./WindowItem";
import With from "./With";
import WithQuery from "./WithQuery";

interface ISyntaxes {
    Any: new (...args: any) => Any;
    Between: new (...args: any) => Between;
    // tslint:disable-next-line: ban-types
    Boolean: new (...args: any) => Boolean;
    ByteString: new (...args: any) => ByteString;
    CacheFor: new (...args: any) => CacheFor;
    CacheReverseExpression: new (...args: any) => CacheReverseExpression;
    CaseWhen: new (...args: any) => CaseWhen;
    CaseWhenElement: new (...args: any) => CaseWhenElement;
    Cast: new (...args: any) => Cast;
    Column: new (...args: any) => Column;
    ColumnLink: new (...args: any) => ColumnLink;
    Comment: new (...args: any) => Comment;
    DataType: new (...args: any) => DataType;
    DollarString: new (...args: any) => DollarString;
    DoubleQuotes: new (...args: any) => DoubleQuotes;
    Exists: new (...args: any) => Exists;
    Expression: new (...args: any) => Expression;
    ExpressionElement: new (...args: any) => ExpressionElement;
    Extract: new (...args: any) => Extract;
    File: new (...args: any) => File;
    FilePathElement: new (...args: any) => FilePathElement;
    FromItem: new (...args: any) => FromItem;
    FunctionCall: new (...args: any) => FunctionCall;
    FunctionLink: new (...args: any) => FunctionLink;
    GroupByElement: new (...args: any) => GroupByElement;
    GroupByElementContent: new (...args: any) => GroupByElementContent;
    In: new (...args: any) => In;
    Interval: new (...args: any) => Interval;
    Join: new (...args: any) => Join;
    ObjectLink: new (...args: any) => ObjectLink;
    ObjectName: new (...args: any) => ObjectName;
    Operator: new (...args: any) => Operator;
    OrderByElement: new (...args: any) => OrderByElement;
    PgArray: new (...args: any) => PgArray;
    PgNull: new (...args: any) => PgNull;
    PgNumber: new (...args: any) => PgNumber;
    SchemaName: new (...args: any) => SchemaName;
    SchemaTable: new (...args: any) => SchemaTable;
    Select: new (...args: any) => Select;
    SelectFetch: new (...args: any) => SelectFetch;
    SingleQuotesString: new (...args: any) => SingleQuotesString;
    SquareBrackets: new (...args: any) => SquareBrackets;
    Substring: new (...args: any) => Substring;
    SystemVariable: new (...args: any) => SystemVariable;
    TableLink: new (...args: any) => TableLink;
    Union: new (...args: any) => Union;
    ValueItem: new (...args: any) => ValueItem;
    ValuesRow: new (...args: any) => ValuesRow;
    WindowDefinition: new (...args: any) => WindowDefinition;
    WindowDefinitionFrame: new (...args: any) => WindowDefinitionFrame;
    WindowDefinitionFrameElement: new (...args: any) => WindowDefinitionFrameElement;
    WindowItem: new (...args: any) => WindowItem;
    With: new (...args: any) => With;
    WithQuery: new (...args: any) => WithQuery;
}

export default ISyntaxes;
